settings:
  preset: "simple"
  generate_all_exports: True

layers:
  domain:
    entities: User, Admin
    value_objects: Email, Password
  application:
    exceptions: UserNotFoundException, UserBlockedException
  infrastructure:
    repositories: UserRepository, AdminRepository
  interface:
    controllers: UserController, AdminController
