settings:
  preset: "standard"

layers:
  domain:
    contexts:
      - name: user
        entities: [User, Profile]
        value_objects: [Email, Password]
        repositories: [UserRepository]
      - name: catalog
        entities: [Product, Category]
        repositories: [ProductRepository]

  application:
    contexts:
      - name: user
        use_cases: [RegisterUser, LoginUser]
      - name: catalog
        use_cases: [ListProducts, SearchProducts]
