single_form_words = {
    "entities": "entity",
    "repositories": "repository",
    "services": "service",
    "value_objects": "value_object",
    "aggregates": "aggregate",
    "factories": "factory",
    "domain_events": "domain_event",
    "commands": "command",
    "queries": "query",
    "exceptions": "exception",
    "controllers": "controller",
    "dto": "dto",
    "models": "model",
    "adapters": "adapter",
    "handlers": "handler",
    "validators": "validator",
    "specifications": "specification",
}
